# Generated by Django 4.2 on 2024-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_learn', '0002_producto_created_at_productrecomender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod',
            field=models.CharField(max_length=255, verbose_name='Producto'),
        ),
    ]
